### Data Mining and Machine Learning
### Ensembles of classifiers
#### Edgar Acuna
#### November 2018

In [3]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import tree
from sklearn import metrics
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
import h2o
from h2o.estimators.gbm import H2OGradientBoostingEstimator
h2o.init(ip="localhost", port=54323)
#h2o.no_progress()

Checking whether there is an H2O instance running at http://localhost:54323. connected.


--------------------------  --------------------------------
H2O cluster uptime:         29 mins 02 secs
H2O cluster timezone:       America/La_Paz
H2O data parsing timezone:  UTC
H2O cluster version:        3.20.0.9
H2O cluster version age:    5 months and 26 days !!!
H2O cluster name:           H2O_from_python_edgar2017_vsqu16
H2O cluster total nodes:    1
H2O cluster free memory:    1.623 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54323
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Algos, AutoML, Core V3, Core V4
Python version:             2.7.13 final
--------------------------  --------------------------------

In [4]:
x=[5,3,12,13,21,31,8,9,15,17,24,32] 

In [5]:
boot1=np.random.choice(x,12)
print boot1

[21  9 24  5 17  9 31 32 13 31  9 21]


In [6]:
np.unique(boot1)

array([ 5,  9, 13, 17, 21, 24, 31, 32])

In [7]:
boot2=np.random.choice(x,12)
print boot2

[15 12  9  9 31 17 31  5 21  3  5 13]


In [8]:
np.unique(boot2)

array([ 3,  5,  9, 12, 13, 15, 17, 21, 31])

Note: Approximately 37% of the  instances of the training sample  L DO NOT appear in any bootstrap sample. In the above examples 16.67% and 41.67% of instances do not appear in each  of the bootstrap samples.

### I. Bagging for Diabetes using trees and scikit learn

In [12]:
url= "http://academic.uprm.edu/eacuna/diabetes.dat"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_table(url, names=names,header=None)
#The response varaiable must be binary  (0,1)
y=data['class']-1
X=data.iloc[:,0:8]
modeltree = tree.DecisionTreeClassifier()
bagging = BaggingClassifier(modeltree,n_estimators=100)

In [13]:
data1=pd.read_csv("c://PW-PR/flights.csv")
data1.head()

YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
0  2015      1    1            4      AS             98      N407AS   
1  2015      1    1            4      AA           2336      N3KUAA   
2  2015      1    1            4      US            840      N171US   
3  2015      1    1            4      AA            258      N3HYAA   
4  2015      1    1            4      AS            135      N527AS   

  ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE      ...        \
0            ANC                 SEA                    5      ...         
1            LAX                 PBI                   10      ...         
2            SFO                 CLT                   20      ...         
3            LAX                 MIA                   20      ...         
4            SEA                 ANC                   25      ...         

   ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  CANCELLATION_REASON  \
0         408.0          -22.0         0          0                  NaN   
1         741.0           -9.0         0          0                  NaN   
2         811.0            5.0         0          0                  NaN   
3         756.0           -9.0         0          0                  NaN   
4         259.0          -21.0         0          0                  NaN   

   AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
0               NaN             NaN            NaN                  NaN   
1               NaN             NaN            NaN                  NaN   
2               NaN             NaN            NaN                  NaN   
3               NaN             NaN            NaN                  NaN   
4               NaN             NaN            NaN                  NaN   

   WEATHER_DELAY  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  

[5 rows x 31 columns]

In [14]:
data2=data1.query('ORIGIN_AIRPORT=="SJU"')

In [15]:
data2.head()

YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
37  2015      1    1            4      UA           1528      N76519   
39  2015      1    1            4      B6            304      N607JB   
45  2015      1    1            4      B6           1990      N597JB   
51  2015      1    1            4      B6            262      N627JB   
52  2015      1    1            4      B6           2134      N307JB   

   ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE      ...        \
37            SJU                 EWR                  154      ...         
39            SJU                 JFK                  155      ...         
45            SJU                 EWR                  206      ...         
51            SJU                 BOS                  330      ...         
52            SJU                 MCO                  400      ...         

    ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  CANCELLATION_REASON  \
37         458.0          -11.0         0          0                  NaN   
39         501.0           11.0         0          0                  NaN   
45         516.0            4.0         0          0                  NaN   
51         619.0          -16.0         0          0                  NaN   
52         730.0           85.0         0          0                  NaN   

    AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
37               NaN             NaN            NaN                  NaN   
39               NaN             NaN            NaN                  NaN   
45               NaN             NaN            NaN                  NaN   
51               NaN             NaN            NaN                  NaN   
52               0.0             0.0           85.0                  0.0   

    WEATHER_DELAY  
37            NaN  
39            NaN  
45            NaN  
51            NaN  
52            0.0  

[5 rows x 31 columns]

In [16]:
data2.describe()

YEAR         MONTH           DAY   DAY_OF_WEEK  FLIGHT_NUMBER  \
count  24656.0  24656.000000  24656.000000  24656.000000   24656.000000   
mean    2015.0      6.218081     15.737103      4.093811    1170.964390   
std        0.0      3.458632      8.818235      2.030232     785.314292   
min     2015.0      1.000000      1.000000      1.000000       4.000000   
25%     2015.0      3.000000      8.000000      2.000000     648.000000   
50%     2015.0      6.000000     16.000000      4.000000    1052.000000   
75%     2015.0      9.000000     23.000000      6.000000    1554.000000   
max     2015.0     12.000000     31.000000      7.000000    6871.000000   

       SCHEDULED_DEPARTURE  DEPARTURE_TIME  DEPARTURE_DELAY      TAXI_OUT  \
count         24656.000000    24474.000000     24474.000000  24466.000000   
mean           1332.906676     1343.083027        10.150609     13.382245   
std             478.760527      491.009889        45.252550      4.829110   
min              49.000000        1.000000       -28.000000      1.000000   
25%            1009.000000     1018.000000        -6.000000     10.000000   
50%            1423.000000     1429.000000        -2.000000     12.000000   
75%            1701.000000     1715.000000         9.000000     15.000000   
max            2305.000000     2359.000000      1330.000000     95.000000   

         WHEELS_OFF      ...        SCHEDULED_ARRIVAL  ARRIVAL_TIME  \
count  24466.000000      ...             24656.000000  24462.000000   
mean    1367.185891      ...              1597.886153   1564.741926   
std      489.402174      ...               517.299882    546.902588   
min        1.000000      ...                 8.000000      1.000000   
25%     1029.000000      ...              1253.000000   1220.000000   
50%     1443.000000      ...              1715.000000   1703.000000   
75%     1728.000000      ...              2000.000000   1957.000000   
max     2400.000000      ...              2359.000000   2400.000000   

       ARRIVAL_DELAY      DIVERTED     CANCELLED  AIR_SYSTEM_DELAY  \
count   24399.000000  24656.000000  24656.000000       4308.000000   
mean        2.519693      0.002677      0.007747          8.227948   
std        46.616979      0.051670      0.087675         17.107889   
min       -62.000000      0.000000      0.000000          0.000000   
25%       -16.000000      0.000000      0.000000          0.000000   
50%        -7.000000      0.000000      0.000000          0.000000   
75%         6.000000      0.000000      0.000000         13.000000   
max      1321.000000      1.000000      1.000000        251.000000   

       SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  WEATHER_DELAY  
count     4308.000000    4308.000000          4308.000000    4308.000000  
mean         0.146936      22.050836            31.582637       0.567549  
std          1.810245      69.651049            53.928724      14.451936  
min          0.000000       0.000000             0.000000       0.000000  
25%          0.000000       0.000000             0.000000       0.000000  
50%          0.000000       6.000000            14.000000       0.000000  
75%          0.000000      18.000000            39.000000       0.000000  
max         55.000000    1316.000000           869.000000     819.000000  

[8 rows x 26 columns]

In [17]:
# Accuracy rate
bagging.fit(X, y)
predictions = bagging.predict(X)
print(classification_report(y, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       500
           1       1.00      1.00      1.00       268

   micro avg       1.00      1.00      1.00       768
   macro avg       1.00      1.00      1.00       768
weighted avg       1.00      1.00      1.00       768



In [18]:
#Estimating the accuracy by cross validation
kfold = model_selection.KFold(n_splits=10, random_state=99)
results = model_selection.cross_val_score(bagging, X, y, cv=kfold)
print(results.mean())

0.7642002734107998


#### Out-of-Bag accuracy

In [19]:
bagging1 = BaggingClassifier(modeltree,n_estimators=100, oob_score=True)
bagging1.fit(X, y)
bagging1.score(X,y)

1.0

### II. AdaBoosting para Diabetes usando scikit-learn

In [20]:
adaboost = AdaBoostClassifier(modeltree,n_estimators=100,learning_rate=1)
adaboost.fit(X, y)
predictions = adaboost.predict(X)
print(classification_report(y, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       500
           1       1.00      1.00      1.00       268

   micro avg       1.00      1.00      1.00       768
   macro avg       1.00      1.00      1.00       768
weighted avg       1.00      1.00      1.00       768



In [21]:
kfold = model_selection.KFold(n_splits=10, random_state=999)
results = model_selection.cross_val_score(adaboost, X, y, cv=kfold)
print(results.mean())

0.6965140123034861


### III. Gradient Boosting para Diabetes usando scikit-learn

In [22]:
gboost = GradientBoostingClassifier(n_estimators=100)
#X_train, X_train_lr, y_train, y_train_lr = train_test_split(X,y,test_size=0.5)
gboost.fit(X, y)
predictions = gboost.predict(X)
print(classification_report(y, predictions))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93       500
           1       0.91      0.81      0.86       268

   micro avg       0.91      0.91      0.91       768
   macro avg       0.91      0.88      0.89       768
weighted avg       0.91      0.91      0.90       768



In [23]:
kfold = model_selection.KFold(n_splits=10, random_state=999)
results = model_selection.cross_val_score(gboost, X, y, cv=kfold)
print(results.mean())

0.7669002050580999


### IV  Gradient Boosting for diabetes using h2o

In [24]:
diabetes = h2o.import_file("https://academic.uprm.edu/eacuna/diabetes.dat")
myx=['C1','C2','C3','C4','C5','C6','C7','C8']
diabetes['C9']=diabetes['C9'].asfactor()
myy="C9"
gbm1 = H2OGradientBoostingEstimator(model_id="gbm_covType_v1",ntrees = 100, max_depth=3,nfolds=10, sample_rate = 1,col_sample_rate = 1,seed=2000000
)
gbm1.train(myx, myy, training_frame=diabetes)
y_pred=gbm1.predict(diabetes)
print (y_pred['predict']==diabetes['C9']).mean()

Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
gbm prediction progress: |████████████████████████████████████████████████| 100%
[0.9010416666666666]


In [25]:
gbm1.model_performance(diabetes)


ModelMetricsBinomial: gbm
** Reported on test data. **

MSE: 0.0850512740729
RMSE: 0.291635515795
LogLoss: 0.288616025631
Mean Per-Class Error: 0.113776119403
AUC: 0.958287313433
Gini: 0.916574626866
Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.490897342808: 


1    2    Error    Rate
-----  ---  ---  -------  ------------
1      477  23   0.046    (23.0/500.0)
2      52   216  0.194    (52.0/268.0)
Total  529  239  0.0977   (75.0/768.0)

Maximum Metrics: Maximum metrics at their respective thresholds



metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.490897     0.852071  159
max f2                       0.311824     0.894625  228
max f0point5                 0.509946     0.888047  153
max accuracy                 0.499875     0.902344  155
max precision                0.987442     1         0
max recall                   0.0696505    1         346
max specificity              0.987442     1         0
max absolute_mcc             0.499875     0.782556  155
max min_per_class_accuracy   0.406007     0.876     196
max mean_per_class_accuracy  0.376373     0.886224  206

Gains/Lift Table: Avg response rate: 34.90 %, avg score: 34.91 %



group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain
--  -------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------
    1        0.0104167                   0.960701           2.86567   2.86567            1                0.969585   1                           0.969585            0.0298507       0.0298507                  186.567   186.567
    2        0.0208333                   0.950231           2.86567   2.86567            1                0.95486    1                           0.962223            0.0298507       0.0597015                  186.567   186.567
    3        0.03125                     0.937274           2.86567   2.86567            1                0.940809   1                           0.955085            0.0298507       0.0895522                  186.567   186.567
    4        0.0403646                   0.927691           2.86567   2.86567            1                0.932931   1                           0.950082            0.0261194       0.115672                   186.567   186.567
    5        0.0507812                   0.916885           2.86567   2.86567            1                0.923115   1                           0.94455             0.0298507       0.145522                   186.567   186.567
    6        0.10026                     0.864848           2.86567   2.86567            1                0.89148    1                           0.91836             0.141791        0.287313                   186.567   186.567
    7        0.151042                    0.791834           2.79219   2.84097            0.974359         0.833701   0.991379                    0.889897            0.141791        0.429104                   179.219   184.097
    8        0.200521                    0.687437           2.48861   2.75402            0.868421         0.741434   0.961039                    0.853263            0.123134        0.552239                   148.861   175.402
    9        0.300781                    0.504609           2.34464   2.61756            0.818182         0.596434   0.91342                     0.767653            0.235075        0.787313                   134.464   161.756
    10       0.39974                     0.383516           1.09348   2.24026            0.381579         0.445912   0.781759                    0.688004            0.108209        0.895522                   9.348     124.026
    11       0.5                         0.232383           0.632681  1.91791            0.220779         0.306749   0.669271                    0.611554            0.0634328       0.958955                   -36.7319  91.791
    12       0.60026                     0.143175           0.334949  1.65351            0.116883         0.188011   0.577007                    0.540811            0.0335821       0.992537                   -66.5051  65.3511
    13       0.699219                    0.0961452          0         1.41949            0                0.118137   0.495345                    0.480991            0               0.992537                   -100      41.9495
    14       0.799479                    0.051558           0.074433  1.25081            0.025974         0.0722341  0.436482                    0.42973             0.00746269      1                          -92.5567  25.0814
    15       0.89974                     0.0257828          0         1.11143            0                0.0377247  0.387844                    0.386048            0               1                          -100      11.1433
    16       1                           0.00771323         0         1                  0                0.0170934  0.348958                    

### V. Bagging  using Decision Trees for Landsat (scikit-learn)

In [26]:
url='http://academic.uprm.edu/eacuna/landsat.txt'
data = pd.read_table(url, header=None,delim_whitespace=True)
y=data.iloc[:,36]-1
names=['C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12','C13',
            'C14','C15','C16','C17','C18','C19','C20','C21','C22','C23','C24','C25','C26','C27',
           'C28','C29', 'C30','C31','C32','C33','C34','C35','C36','C37']
X=data.iloc[:,0:36]
modeltree = tree.DecisionTreeClassifier()
bagging = BaggingClassifier(modeltree,n_estimators=100, max_features=1.0)
# Tasa de precision
bagging.fit(X, y)
predictions = bagging.predict(X)
print(classification_report(y, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1072
           1       1.00      1.00      1.00       479
           2       1.00      1.00      1.00       961
           3       1.00      1.00      1.00       415
           4       1.00      1.00      1.00       470
           5       1.00      1.00      1.00      1038

   micro avg       1.00      1.00      1.00      4435
   macro avg       1.00      1.00      1.00      4435
weighted avg       1.00      1.00      1.00      4435



In [27]:
kfold = model_selection.KFold(n_splits=10, random_state=99)
results = model_selection.cross_val_score(modeltree, X, y, cv=kfold)
print(results.mean())

0.7991092672808249
